# Generated by Django 3.2.7 on 2021-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('choseprogress', models.CharField(choices=[('Todo', 'Todo'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
