# Generated by Django 3.2.7 on 2021-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
